version: '3.8'

services:
  web:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./projecteVideojocs_front:/usr/local/apache2/htdocs/

  node:
    image: node:16
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./projecteVideojocs_server:/app
    command: sh -c "npm install && node index.js"

  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: iesmanacorroot
      MYSQL_USER: daw
      MYSQL_PASSWORD: iesmanacor
      MYSQL_DATABASE: practicadaw
    ports:
      - "3306:3306"
    volumes:
      - ./volums/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db